spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/utn_phones
    username: franco
    password: a

  liquibase:
    user: franco
    password: a
    url: jdbc:mysql://localhost:3306/utn_phones
    change-log: db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html