spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/utn_phones
    username: franco
    password: a

  liquibase:
    user: franco
    password: a
    url: jdbc:mysql://localhost:3306/utn_phones
